[package]
name = "sea-forge-settlement"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "SEA Forge settlement evaluation."

[dependencies]
sea-forge-core = { path = "../sea-forge-core", version = "0.1.0" }
sea-forge-sandbox = { path = "../sea-forge-sandbox", version = "0.1.0" }
chrono.workspace = true

[lints]
workspace = true
