[package]
name = "sea-forge-trace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "SEA Forge trace event recording."

[dependencies]
sea-forge-core = { path = "../sea-forge-core", version = "0.1.0" }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
