//! Convergence plan T04 — governed work submission at the SEA-Forge boundary
//! (frozen edge E4).
//!
//! The golden fixture is REAL producer output from SWE_SEED's canonical
//! GovernedWorkRequest emitter (`swe-seed-core` federation::
//! `build_governed_work_request`, regenerated by its
//! convergence_t04_governed_submission suite). These tests run that output
//! plus adversarial mutations through the real acceptance gate
//! (`governed_work_ingress::accept_governed_work_request`).
//!
//! Plan teeth:
//!   TEETH-1 opaque command-only request  -> cannot settle as GovernedWorkRequest
//!   TEETH-2 context packet cross-wire    -> rejected
//!   TEETH-3 different DomainForge model  -> rejected before governed execution

use serde_json::{json, Value};

use sea_forge_server::governed_work_ingress::{accept_governed_work_request, GovernedIngressError};

/// Load the cross-repo fixture: real SWE_SEED emitter output plus the
/// out-of-band local model digest SEA-Forge resolves independently.
fn fixture() -> Option<Value> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/t04_governed_work_request.json");
    let Ok(body) = std::fs::read_to_string(&path) else {
        eprintln!(
            "SKIP: fixture not found at {} (run swe-seed-core convergence_t04_governed_submission to generate)",
            path.display()
        );
        return None;
    };
    Some(serde_json::from_str(&body).expect("fixture must be valid JSON"))
}

fn accept(body: &Value, local: &str) -> Result<(), GovernedIngressError> {
    accept_governed_work_request(&body["request"], &body["context_packet"], local).map(|_| ())
}

fn other_digest(seed: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    format!("{:x}", Sha256::digest(seed))
}

// --- E4 happy path: real producer output through the real gate -----------------

#[test]
fn e4_golden_fixture_from_swe_seed_producer_is_accepted() {
    let Some(body) = fixture() else { return };
    let local = body["domain_model_sha256"].as_str().unwrap();
    let intent = accept_governed_work_request(&body["request"], &body["context_packet"], local)
        .expect("real emitter output must pass the acceptance gate");
    assert_eq!(intent.work_request_id, "wr-gsf-001");
    assert_eq!(intent.affordance_id, "aff-blue-green-001");
    assert_eq!(intent.actor_id, "agent-operator");
    assert_eq!(intent.context_packet_ref, "ctx_01J9T04PACKET0000000000");
    assert!(!intent.intent.is_empty());
    assert!(intent.proof_contract.get("criterion").is_some());
    assert!(!intent.settlement_criteria.is_empty());
}

// --- frozen falsifier: opaque command-only requests ------------------------------

#[test]
fn t04_opaque_command_only_request_cannot_settle() {
    let Some(mut body) = fixture() else { return };
    // Executable detail only: argv/command with no semantic work intent.
    body["request"]["payload"] = json!({
        "namespace": "agentic_capability_loop",
        "domain_model_hash": body["domain_model_sha256"],
        "work_request_id": "wr-gsf-001",
        "argv": ["/bin/deploy", "--force"],
        "command": "/bin/deploy --force",
    });
    let err = accept_governed_work_request(
        &body["request"],
        &body["context_packet"],
        body["domain_model_sha256"].as_str().unwrap(),
    )
    .unwrap_err();
    match err {
        GovernedIngressError::OpaqueCommand { missing } => {
            for field in [
                "affordance_id",
                "actor",
                "intent",
                "context_packet_ref",
                "proof_contract",
                "settlement_criteria",
            ] {
                assert!(
                    missing.contains(&field),
                    "{field} must be reported missing: {missing:?}"
                );
            }
        }
        other => panic!("expected OpaqueCommand, got {other}"),
    }
}

#[test]
fn t04_empty_semantic_fields_are_opaque_commands_too() {
    let Some(mut body) = fixture() else { return };
    body["request"]["payload"]["intent"] = json!("   ");
    body["request"]["payload"]["settlement_criteria"] = json!([]);
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::OpaqueCommand { ref missing }
            if missing.contains(&"intent") && missing.contains(&"settlement_criteria")),
        "{err}"
    );
}

// --- frozen falsifier: cross-wired context packets -------------------------------

#[test]
fn t04_cross_wired_context_packet_is_rejected() {
    let Some(mut body) = fixture() else { return };
    // A structurally valid packet that belongs to someone else's cycle.
    body["context_packet"]["payload"]["work_request_id"] = json!("wr-OTHER-CYCLE");
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::CrossWiredContextPacket { ref expected, ref got }
            if expected == "wr-gsf-001" && got == "wr-OTHER-CYCLE"),
        "{err}"
    );
}

#[test]
fn t04_swapped_in_foreign_packet_is_rejected() {
    let Some(body) = fixture() else { return };
    let mut foreign = body["request"].clone();
    foreign["event_type"] = json!("ContextPacketCreated");
    foreign["source_agent"] = json!("context-kernel");
    foreign["event_id"] = json!("11111111-2222-4333-8444-555555555555");
    foreign["payload"] = json!({
        "namespace": "agentic_capability_loop",
        "domain_model_hash": body["domain_model_sha256"],
        "work_request_id": "wr-FOREIGN",
        "context_requirement_id": "cr-x",
        "context_packet_id": "ctx_FOREIGN",
        "citations": [{"source": "x", "sha256": "aa"}],
    });
    let err = accept_governed_work_request(
        &body["request"],
        &foreign,
        body["domain_model_sha256"].as_str().unwrap(),
    )
    .unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::CrossWiredContextPacket { .. }),
        "{err}"
    );
}

// --- frozen falsifier: different DomainForge model --------------------------------

#[test]
fn t04_different_domain_model_is_rejected() {
    let Some(body) = fixture() else { return };
    // SEA-Forge resolves a DIFFERENT (valid) canonical model locally.
    let local = other_digest(b"a-different-canonical-model");
    let err = accept(&body, &local).unwrap_err();
    match err {
        GovernedIngressError::DomainDrift {
            declared,
            local: local_got,
        } => {
            assert_eq!(declared, body["domain_model_sha256"].as_str().unwrap());
            assert_eq!(local_got, local);
        }
        other => panic!("expected DomainDrift, got {other}"),
    }
}

#[test]
fn t04_drift_on_the_referenced_context_packet_is_rejected_too() {
    let Some(mut body) = fixture() else { return };
    body["context_packet"]["payload"]["domain_model_hash"] = json!(other_digest(b"drifted"));
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::DomainDrift { .. }),
        "{err}"
    );
}

// --- placeholder/fallback pseudo-identities ---------------------------------------

#[test]
fn t04_placeholder_pseudo_identity_is_rejected() {
    use sha2::{Digest, Sha256};
    let Some(mut body) = fixture() else { return };

    // The standalone fallback constant.
    let mut h = Sha256::new();
    h.update(b"agentic_capability_loop");
    let fallback = format!("{:x}", h.finalize());
    body["request"]["payload"]["domain_model_hash"] = json!(fallback.clone());
    body["context_packet"]["payload"]["domain_model_hash"] = json!(fallback.clone());
    let err = accept(&body, &fallback).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::PlaceholderIdentity { .. }),
        "fallback constant must never settle: {err}"
    );

    // All-zero digest and malformed short hashes are equally refused.
    body["request"]["payload"]["domain_model_hash"] = json!("0".repeat(64));
    assert!(matches!(
        accept(&body, &"0".repeat(64)),
        Err(GovernedIngressError::PlaceholderIdentity { .. })
    ));
    body["request"]["payload"]["domain_model_hash"] = json!("deadbeef");
    assert!(matches!(
        accept(&body, "deadbeef"),
        Err(GovernedIngressError::PlaceholderIdentity { .. })
    ));
}

// --- exclusive producer stamps ------------------------------------------------------

#[test]
fn t04_non_swe_seed_producer_stamp_is_rejected() {
    let Some(mut body) = fixture() else { return };
    for forger in [
        "godspeed-agent",
        "context-kernel",
        "sea-forge",
        "mystery-agent",
    ] {
        body["request"]["source_agent"] = json!(forger);
        let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
        assert!(
            matches!(
                err,
                GovernedIngressError::NotAuthoritative {
                    authoritative: "swe_seed",
                    ..
                } | GovernedIngressError::UnknownAgent { .. }
            ),
            "forger {forger} must be rejected: {err}"
        );
    }

    // The referenced packet must genuinely come from context_kernel.
    body = fixture().unwrap();
    body["context_packet"]["source_agent"] = json!("swe-seed");
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::NotAuthoritative { .. }),
        "self-produced packet must be rejected: {err}"
    );
}

// --- distinct proof / settlement obligations -----------------------------------------

#[test]
fn t04_proof_contract_may_not_collapse_into_settlement_criteria() {
    let Some(mut body) = fixture() else { return };
    let criteria = body["request"]["payload"]["settlement_criteria"].clone();
    // Collapsed: proof contract replaced by the criteria array itself.
    body["request"]["payload"]["proof_contract"] = criteria.clone();
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::CollapsedObligations),
        "{err}"
    );

    // Vanished obligation: object shape without a criterion inside.
    body["request"]["payload"]["proof_contract"] = json!({"command": "run something"});
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::OpaqueCommand { ref missing }
            if missing.contains(&"proof_contract.criterion")),
        "{err}"
    );
}

// --- reference + causality binding -----------------------------------------------------

#[test]
fn t04_context_ref_to_another_packet_is_rejected() {
    let Some(mut body) = fixture() else { return };
    body["request"]["payload"]["context_packet_ref"] = json!("ctx_SOMETHING_ELSE");
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    assert!(
        matches!(err, GovernedIngressError::ContextRefMismatch { ref declared_ref, .. }
            if declared_ref == "ctx_SOMETHING_ELSE"),
        "{err}"
    );
}

#[test]
fn t04_lost_causal_lineage_is_rejected() {
    let Some(mut body) = fixture() else { return };
    body["request"]["provenance"]["chain"] = json!([]);
    let err = accept(&body, body["domain_model_sha256"].as_str().unwrap()).unwrap_err();
    match err {
        GovernedIngressError::CausalityMissing {
            expected_parent,
            recorded,
        } => {
            assert_eq!(expected_parent, body["context_packet"]["event_id"]);
            assert!(recorded.is_empty());
        }
        other => panic!("expected CausalityMissing, got {other}"),
    }
}
