(function () {
  const shell = document.querySelector(".app-shell");
  const main = document.querySelector("#main-content");
  const drawer = document.querySelector("#drawerContent");
  const drawerTitle = document.querySelector("#drawerTitle");
  const live = document.querySelector("#liveRegion");
  let route = "Readiness";
  let tab = "why";

  const pill = (type, label) => '<span class="status-pill status-pill--' + type + '">' + label + '</span>';
  const drawerButton = (label, target) => '<button class="button" type="button" data-drawer="' + target + '">' + label + '</button>';
  const header = (title, state, reason, projection, action, id) => '<section class="governed-focus" data-od-id="' + id + '" data-state="' + state + '"><div class="focus-copy"><div class="title-line"><h1>' + title + '</h1>' + pill(state === "ready" ? "ready" : state === "blocked" ? "blocked" : "degraded", state === "ready" ? "● Source current" : state === "blocked" ? "■ Authority escalated" : "▲ Review required") + '</div><p>' + reason + '</p><div class="focus-meta"><button class="freshness-badge" type="button" data-drawer="provenance"><span class="state-dot state-dot--ready"></span>Source current · copied specifications</button><span class="machine-value">Projection: ' + projection + '</span></div></div><div class="focus-actions">' + drawerButton("Why this state", "why") + '<button class="button button--primary" type="button" data-action="' + id + '">' + action + '</button></div></section>';
  const ribbon = (active) => '<div class="journey-ribbon" aria-label="Governed journey"><strong>' + active + '</strong><span>Authority</span><span>Domain</span><span>Draft</span><span>Preflight</span><span>Execution</span><span>Evidence</span><span>Settlement</span></div>';
  const row = (name, detail, label, type, reason, source) => '<button class="condition-row" type="button" role="row" data-drawer="evidence"><span><strong>' + name + '</strong><small>' + detail + '</small></span><span>' + pill(type, label) + '</span><span>' + reason + '</span><span class="machine-value">' + source + '</span></button>';
  const panel = (kicker, title, body, id) => '<section class="panel" data-od-id="' + (id || "route-panel") + '"><div class="section-header"><div><p class="section-kicker">' + kicker + '</p><h2>' + title + '</h2></div></div>' + body + '</section>';

  const views = {
    Readiness: () => ribbon("Readiness") + header("Readiness Overview", "degraded", "Core local execution is available. External agent delegation requires endpoint verification.", "readiness / intended operation", "Run checks", "readiness") + '<div class="content-grid"><div class="content-primary">' + panel("Operation-sensitive readiness", "What do you intend to do?", '<div class="segmented-control" role="radiogroup"><button class="segment" type="button" data-operation="local">Run local governed work</button><button class="segment segment--active" type="button" data-operation="agent">Delegate to external agent</button><button class="segment" type="button" data-operation="federation">Import governed bundle</button></div><p class="operation-explanation" id="operationExplanation">This path needs a verified endpoint and an allowed authority boundary before commitment.</p>', "intended-work-selector") + panel("Required conditions", "Critical foundations", '<div class="condition-table" role="table"><div class="condition-row condition-row--header" role="row"><span>Foundation</span><span>State</span><span>Reason</span><span>Source</span></div>' + row("Cell integrity", "Ledger and local state", "Integrity verified", "ready", "Required integrity checks pass.", "DESIGN.md") + row("Actor context", "Identity and sponsorship", "Authority allowed", "ready", "Operator and sponsor are visible.", "UX epic §2") + row("Agent endpoint", "External delegation", "Readiness degraded", "degraded", "Endpoint verification has not been recorded.", "Atomic §4.4") + '</div>', "critical-foundations") + panel("Current affordances", "Operational capabilities", '<div class="capability-list"><div class="capability-row"><div><strong>Local governed execution</strong><span>Spendable for this actor and policy context</span></div>' + pill("ready", "Capability proven") + '</div><div class="capability-row"><div><strong>External agent delegation</strong><span>Limited by endpoint verification</span></div>' + pill("degraded", "Capability degraded") + '</div></div>', "operational-capabilities") + '</div><aside class="attention-rail">' + panel("Current limitation", "Endpoint verification required", '<p>A source-backed endpoint probe must complete before external delegation becomes spendable.</p><dl class="key-values"><div><dt>Affects</dt><dd>Agent task start</dd></div><div><dt>Authority</dt><dd>Operator may probe</dd></div></dl>' + drawerButton("Open endpoint evidence", "evidence"), "readiness-limitation") + '</aside></div>',
    Thoth: () => ribbon("Thoth") + header("Thoth workspace", "ready", "A typed question can be grounded in selected source records. Drafting an answer does not change a case.", "grounded answer / disclosure", "Ask Thoth", "thoth") + '<div class="content-grid"><div class="content-primary">' + panel("Grounded question", "What should be inspected?", '<label class="field-label" for="thothQuestion">Question</label><textarea id="thothQuestion" class="workbench-input" rows="3">What is missing before external agent delegation is spendable?</textarea><div class="source-chip-row"><span class="machine-value">3 selected sources · disclosure required</span></div>', "thoth-question-composer") + panel("Answer detail", "Grounded answer", '<p class="operational-copy">Endpoint verification and an allowed authority boundary are both required before delegation becomes spendable. The current projection records no endpoint-verification evidence.</p><button class="evidence-link" type="button" data-drawer="evidence"><strong>Readiness screen contract</strong><span>Primary path §3</span></button><button class="evidence-link" type="button" data-drawer="provenance"><strong>Authority boundary</strong><span>UX epic §4.6</span></button>', "thoth-answer-detail") + '</div><aside class="attention-rail">' + panel("Answer standing", "Not a decision", '<p>This answer is an inspection aid. It does not approve, commit, or execute work.</p>', "thoth-standing") + '</aside></div>',
    Assets: () => ribbon("Assets") + header("Asset catalog", "ready", "Available assets are separate from declared and installed assets. Imported material remains inert until reviewed.", "catalog / availability", "Inspect selected asset", "assets") + '<div class="content-grid"><div class="content-primary">' + panel("Availability ladder", "Governed assets", '<div class="asset-table" role="table"><div class="asset-row asset-row--header"><span>Name</span><span>Availability</span><span>Compatibility</span><span>Evidence</span></div><button class="asset-row" type="button" data-drawer="evidence"><strong class="machine-value">repair.tests</strong>' + pill("ready", "Available") + '<span>Compatible with current policy</span><span class="machine-value">JUnit manifest</span></button><button class="asset-row" type="button" data-drawer="evidence"><strong class="machine-value">agent-kit/repair</strong>' + pill("neutral", "Installed") + '<span>Endpoint validation stale</span><span class="machine-value">Install record</span></button><button class="asset-row" type="button" data-drawer="why"><strong class="machine-value">external/triage-bundle</strong>' + pill("degraded", "Declared") + '<span>Inspection required before adoption</span><span class="machine-value">Bundle digest</span></button></div>', "asset-catalog-table") + panel("Selected asset", "repair.tests", '<dl class="detail-grid"><div><dt>Version</dt><dd class="machine-value">1.4.2</dd></div><div><dt>Producer</dt><dd>Local test suite</dd></div><div><dt>Compatibility</dt><dd>Policy PB-14</dd></div><div><dt>Evidence</dt><dd>JUnit report required</dd></div></dl>', "asset-detail") + '</div><aside class="attention-rail">' + panel("Import boundary", "External bundle is inert", '<p>Inspection can stage the bundle. It cannot adopt it automatically.</p>' + drawerButton("Why this boundary", "why"), "asset-boundary") + '</aside></div>',
    "Domain Models": () => ribbon("Domain") + header("Domain models", "degraded", "The active repair model is structurally valid. Its agent endpoint projection is stale and cannot support an execution claim.", "model / validation", "Validate model", "domain") + '<div class="content-grid workbench-grid"><aside class="panel side-list"><p class="section-kicker">Models</p><button class="list-item list-item--active" type="button">Repair domain <span>current</span></button><button class="list-item" type="button">Service incident</button><button class="list-item" type="button">Escalation policy</button></aside><div class="content-primary">' + panel(".sea source", "Repair domain", '<pre class="model-editor">domain repair {\n  outcome recovery_test: all_pass\n  evidence junit_report: required\n  delegate repair_agent: endpoint_verified\n}</pre>', "domain-model-workbench") + panel("Validation", "Projection checks", '<div class="validation-list"><button class="validation-row" type="button" data-drawer="evidence"><strong>Schema</strong>' + pill("ready", "Validated") + '<span>Current model schema is valid.</span></button><button class="validation-row" type="button" data-drawer="evidence"><strong>Concept references</strong>' + pill("ready", "Resolved") + '<span>Desired outcome and evidence types are linked.</span></button><button class="validation-row" type="button" data-drawer="why"><strong>Agent endpoint</strong>' + pill("degraded", "Stale") + '<span>Endpoint configuration requires refresh before execution.</span></button></div>', "model-validation") + '</div><aside class="attention-rail">' + panel("Model consequence", "Execution unavailable", '<p>The model can be edited and reviewed. It cannot authorize delegation.</p>' + drawerButton("Inspect validation evidence", "evidence"), "model-consequence") + '</aside></div>',
    Cases: () => ribbon("Cases") + header("Case horizon", "degraded", "One committed case is awaiting endpoint evidence. Personal arrangement may change, but authoritative state remains source-backed.", "case reducer / board", "Create draft case", "cases") + '<section class="case-toolbar panel"><div><p class="section-kicker">Case projections</p><h2>Repair agent for recurring service incidents</h2></div><div class="projection-switch"><button class="segment segment--active" type="button">Board</button><button class="segment" type="button">List</button><button class="segment" type="button">Graph</button></div></section><section class="horizon-board" data-od-id="case-horizon-board">' + lane("Spendable now", "Local repair recovery", "ready", "Ready") + lane("Awaiting authority", "External agent repair", "degraded", "Awaiting evidence") + lane("Blocked", "Endpoint validation", "blocked", "Blocked") + lane("Future", "Evidence review", "neutral", "Parked") + '</section>',
    Inbox: () => ribbon("Inbox") + header("Inbox and approvals", "blocked", "Approval APR-07 is pending. The exact resource, authority, expiry, and separation-of-duty condition require review.", "approval / human task", "Review approval", "inbox") + '<div class="content-grid"><div class="content-primary">' + panel("Approval APR-07", "Permit external agent endpoint probe", '<dl class="detail-grid"><div><dt>Requesting actor</dt><dd>Operator</dd></div><div><dt>Sponsor</dt><dd>Service recovery</dd></div><div><dt>Resource</dt><dd class="machine-value">endpoint:repair-agent</dd></div><div><dt>Boundary</dt><dd>Probe only; no task start</dd></div><div><dt>Policy reason</dt><dd>External endpoint lacks current verification</dd></div><div><dt>Separation of duty</dt><dd>Requester may not approve</dd></div></dl><div class="decision-actions">' + drawerButton("Inspect evidence", "evidence") + '<button class="button button--attention" type="button" data-drawer="why">Escalate for decision</button></div>', "approval-decision-panel") + '</div><aside class="attention-rail">' + panel("Decision consequence", "No automatic approval", '<p>Approval does not execute the probe. It only permits the bounded request.</p><p class="machine-value">Expires in 1h 58m</p>', "approval-consequence") + '</aside></div>',
    Operations: () => ribbon("Operations") + header("Operations monitor", "degraded", "Execution completed. Settlement evaluation continues. The event stream is stale after EVT-1182.", "run / event cursor", "Reconnect stream", "operations") + '<div class="content-grid"><div class="content-primary">' + panel("Run RUN-041", "Repair recovery verification", '<div class="dual-state"><div><span>Execution</span>' + pill("ready", "Execution succeeded") + '</div><div><span>Settlement</span>' + pill("degraded", "Settlement evaluating") + '</div></div><div class="event-stream"><div><span class="machine-value">EVT-1182</span><strong>Test command exited 0</strong><small>Execution evidence captured</small></div><div><span class="machine-value">EVT-1183</span><strong>Settlement evaluator queued</strong><small>Awaiting criterion result</small></div><div class="event-stale"><span class="machine-value">CURSOR</span><strong>Live state may be stale. Reconnecting…</strong><small>Last confirmed event remains visible.</small></div></div>', "execution-console") + panel("Evidence inventory", "Settlement preview", '<div class="criterion-row"><strong>Repair recovery test passes</strong>' + pill("ready", "Pass") + '<span>JUnit report</span></div><div class="criterion-row"><strong>Qualifying declaration</strong>' + pill("degraded", "Not evaluated") + '<span>Human reviewer required</span></div>', "settlement-preview") + '</div><aside class="attention-rail">' + panel("Scoped control", "Cancellation is not required", '<p>No active process is running. Retry would create a new episode.</p><button class="button button--disabled" type="button" disabled>Cancel run</button>', "operation-control") + '</aside></div>'
  };

  function lane(title, card, type, status) { return '<section class="horizon-lane horizon-lane--' + type + '"><div><h2>' + title + '</h2><span class="machine-value">1</span></div><button class="case-card" type="button" data-drawer="why"><strong>' + card + '</strong>' + pill(type, status) + '<span>Source-backed case projection</span></button></section>'; }
  const reasons = { Readiness: "External delegation needs a verified endpoint and an authority boundary before the path becomes spendable.", Thoth: "Thoth provides an inspectable grounded answer. It does not create approval, evidence, or execution.", Assets: "Declared, installed, and available assets communicate different operational states.", "Domain Models": "The model is structurally valid, but its endpoint projection is stale for execution.", Cases: "The horizon projects source-backed case state. External work remains blocked on endpoint evidence.", Inbox: "APR-07 requires a separated human decision. Approval does not execute the probe.", Operations: "Execution evidence was captured. Settlement has not evaluated every required criterion." };

  function announce(message) { live.textContent = ""; setTimeout(() => { live.textContent = message; }, 20); }
  function openDrawer(nextTab) { tab = nextTab || tab; shell.classList.remove("drawer-closed"); drawerTitle.textContent = "Why " + route.toLowerCase() + " is constrained"; document.querySelectorAll("[data-tab]").forEach((button) => button.setAttribute("aria-selected", String(button.dataset.tab === tab))); drawer.innerHTML = window.SeaForgeComponents.renderDrawerTab(tab, { title: route + " state", reason: reasons[route] }); }
  function bindView() {
    main.querySelectorAll("[data-drawer]").forEach((button) => button.addEventListener("click", () => openDrawer(button.dataset.drawer)));
    main.querySelectorAll("[data-operation]").forEach((button) => button.addEventListener("click", () => { main.querySelectorAll("[data-operation]").forEach((item) => item.classList.toggle("segment--active", item === button)); const message = { local: "This path is spendable for the active actor and policy context.", agent: "This path needs a verified endpoint and an allowed authority boundary before commitment.", federation: "This path inspects and stages a bundle. It does not adopt imported assets automatically." }[button.dataset.operation]; main.querySelector("#operationExplanation").textContent = message; announce(message); }));
    main.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", () => { if (button.dataset.action === "readiness") { button.textContent = "Checking…"; shell.classList.add("is-checking"); setTimeout(() => { button.textContent = "Run checks"; shell.classList.remove("is-checking"); announce("Readiness projection refreshed. State remains source current."); }, 850); } else { announce(button.textContent + " accepted for inspection. No authoritative state changed."); openDrawer("why"); } }));
  }
  function render(nextRoute) { route = nextRoute; main.innerHTML = views[route](); document.querySelectorAll("[data-route]").forEach((item) => { const active = item.dataset.route === route; item.classList.toggle("nav-item--active", active); item.toggleAttribute("aria-current", active); }); bindView(); openDrawer("why"); announce(route + " workspace selected."); }
  document.querySelectorAll("[data-route]").forEach((item) => item.addEventListener("click", () => render(item.dataset.route)));
  document.querySelectorAll("[data-tab]").forEach((button) => button.addEventListener("click", () => openDrawer(button.dataset.tab)));
  document.querySelector("#closeDrawerButton").addEventListener("click", () => shell.classList.add("drawer-closed"));
  document.addEventListener("keydown", (event) => { if (event.metaKey || event.ctrlKey || event.altKey || event.target.matches("input, textarea, select")) return; if (event.key.toLowerCase() === "e") openDrawer("evidence"); if (event.key === "Escape") shell.classList.add("drawer-closed"); });
  render("Readiness");
  requestAnimationFrame(() => document.documentElement.classList.add("motion-ready"));
})();
